### ISSUE TITLE
What role does target play ?

### ISSUE THREAD

**Issue by prahaladbelavadi** [LinusU/fast-base64-decode#1]
Hey @LinusU 

I'm trying to understand how you're decoding base 64 into bytearray.
I'm having a hard time grasping the role of target and the lookup table since most of the articles I've come  across reference tables like these:
http://www.asciitable.com/index/asciifull.gif
https://tools.ietf.org/html/rfc4648#page-12

Could you direct me to a resource that I could make use of to understand this better ?

Thank you

**Comment by LinusU** [comment]
`target` is the byte array which I decode into. I specifically made this since I had a performance critical path where I wanted to decode data into an already existing array, and I knew the length.

The lookup table is the same as any other base64 table, I've just condensed it into an array and put `0` in every place that isn't used. The index into the array is the ascii-code of the character to decode.

If you want something more highlevel with easier to read code, I would recommend looking at [base64-js](https://github.com/beatgammit/base64-js).

**Comment by prahaladbelavadi** [comment]
Hey @LinusU 
This has been very helpful; Thank you

I did make use of base64-js to write a couple of testcases 
I opened a pull request [here](https://github.com/LinusU/fast-base64-decode/pull/2)

Cheers!
